#%RAML 0.8
title: Competence Management API
version: v1
mediaType:  application/json

/categories:
  post:
    description: create new category
    body:
      application/json:
        example: |
          {
            "name": "Core Competence"
          }
    responses:
      201:
      400:
  /{categoryId}:
    get:
      description: get one category
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": "xxx",
                  "name": "xxx"
                }
        404:
    put:
      body:
        application/json:
          example: |
            {
              "name": "Core Competence"
            }
      responses:
        200:
        400:
        404:
    delete:
      responses:
        404:
        204:
/competences:
  post:
    description: create new competence
    body:
      application/json:
        example: |
          {
            "name": "Self Confidence",
            "description": "A ....",
            "category": "category_id"
          }
    responses:
      201:
      400:
  get:
    description: list competences
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "id": "xxx",
                  "name": "Self Confidence",
                  "description": "A ...",
                  "category": {
                    "id": "xxx",
                    "name": "xxx"
                  },
                  "behaviors": []
                },
                {
                  "id": "xxx",
                  "name": "Self Confidence",
                  "description": "A ...",
                  "category": {
                    "id": "xxx",
                    "name": "xxx"
                  },
                  "behaviors": []
                }
              ]
  /{competenceId}:
    get:
      description: get one competence include all behaviors
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": "xxx",
                  "name": "xx",
                  "description": "xxx",
                  "category": {
                    "id": "xxx",
                    "name": "xxx"
                  },
                  "behaviors": [
                    {
                      "id": "xxx",
                      "name": "xxx",
                      "descriptoin": "xxx"
                    }
                  ]
                }
        404:
    put:
      body:
        application/json:
          example: |
            {
              "name": "Self Confidence",
              "description": "A ....",
              "category": "category_id"
            }
      responses:
        200:
        404:
    delete:
      responses:
        204:
        404:
    /behaviors:
      post:
        description: create new behavior
        body:
          application/json:
            example: |
              {
                "name": "xxx",
                "description": "xxx"
              }
      /{behaviorId}:
        put:
          responses:
            200:
            404:
            400:
        delete:
          responses:
            204:
            404:
