#%RAML 0.8
title: Program API
version: v1
mediaType:  application/json

/programs:
  post:
    description: create new program
    body:
      application/json:
        example: |
          {
            "name": "xxx",
            "description": "xxx",
            "competences": []
          }
    responses:
      201:
      400:
  get:
    description: list all programs
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "count": 10,
                "first": "xx",
                "last": "",
                "prev": "",
                "next": "",
                "items": [
                  {
                    "name": "",
                    "description": ""
                  }
                ]
              }
  /{programId}:
    get:
      description: get program info
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "name": "xx",
                  "description": "xx",
                  "competences": [
                    {
                      "id": "xx",
                      "name": "xxx",
                      "descriptoin": "xx",
                      "category": {
                        "id": "xx",
                        "name": "xxx"
                      },
                      "patterns": [

                      ]
                    }
                  ]
                }
    put:
      description: update program info
      body:
        application/json:
          example: |
            {
              "name": "xxx",
              "description": "xxx",
              "competences": []
            }
      responses:
        200:
        400:
    delete:
      description: remove unpublished program
      responses:
        204:
        404:
        409:
    /published:
      put:
        description: publish program
        responses:
          204:
          404:
          409:
    /assignments:
      post:
        description: add new assignment
        body:
          application/json:
            example: |
              {
                "username": "xxx",
                "role": "coachee",
                "coach": "xxx"
              }
        responses:
          201:
          400:
    /users/{userId}:
      /evidences:
        put:
          description: edit self reflections for this program
          body:
            application/json:
              example: |
                {
                  "evidences": ["123", "1312"]
                }
        get:
          description: show self reflections for this user in this program
          responses:
            200:
              body:
                application/json:
                  example: |
                    [
                      {
                        "content": "xxx",
                        "self_reflection": {
                          "id": "xxx",
                          "createdAt": 123123123,
                          "competence": {
                            "id": "xxx",
                            "name": "xxx",
                            "description": "xxx"
                          },
                          "behavior": {
                            "id": "xxx",
                            "name": "xxx",
                            "description": "xxx"
                          }
                        },
                        "feedbacks": [
                          {
                            "author": {
                              "username": "xxx",
                              "nickname": "xxx"
                            },
                            "approved": true,
                            "comment": "xxx"
                          }
                        ]
                      }
                    ]

/users/{userId}/assignments:
  get:
    description: list all program assignment for one person
